### ISSUE TITLE
Allow contributions targeting ms.vss-work-web.work-item-form to show depending on work item type

### ISSUE THREAD

**Issue by mpseidel** [Microsoft/vss-web-extension-sdk#16]
Different work item types exist for different purposes. 

Some extensions we are building to contribute to the work item form make perfect sense for work items of type User Story or Product Backlog Item, but not so much for Bug, Task, Impediment etc.

Will there be a way to target only specific work item types when writing a contribution with target `ms.vss-work-web.work-item-form`?

**Comment by mmanela** [comment]
We are planning to enable you to configure which work items types you want to an extension to be enabled for in a new admin UI. We considered letting the extension author specify this in their JSON manifest but that is too limiting since users will soon be able to create custom work item types and an extension author would never know what those are.

**Comment by willsmythe** [comment]
@mmanela - can you provide an update on this?

**Comment by mmanela** [comment]
We delivered the ability in the admin UI to configure which types get an extension but we have no immediate plans to be similar logic in the json manifest.

**Comment by dmitry-ra** [comment]
> We delivered the ability in the admin UI to configure which types get an extension

In which TFS release this UI will be published?

Currently I write event observer contribution of type "ms.vss-work-web.work-item-notifications" for target "ms.vss-work-web.work-item-form". And I want to load this contribution only for one Work Item Type, not for the all of them.

**Comment by mmanela** [comment]
For work-item-notifications, this lives above the work item type level and is always listening. You can filter in your extension based on the work items type though.

**Comment by mpseidel** [comment]
Being able to configure this in the admin UI is nice but its not a great solution for extension publishers.

Lets say we build an extension that adds great features inside a new work item tab that make sense only for Bug work items. 

Users now have to actively customize their work item forms to make sure the feature does not show up in User Stories, Tasks etc.

Thoughts?

**Comment by cschleiden** [comment]
Different question: my custom "Bug"-like work item type might be called something completely different, "Defect", maybe. Would you want to prevent me from having your extension show up for my work items?

**Comment by mpseidel** [comment]
No not preventing. I'm not saying customizeability is a bad thing. Far from it. 
But I'd like the experience after installing to be as good as possible and make sense to the user while not being intrusive (showing up in places where it doesn't make sense in 95% of cases).

I don't have a real immediate use case for this today. Just wanted to make sure this is being considered in future planning. Some extension points like the backlog tabs do have a callback to show / hide them dynamically. Maybe that approach could be used more in the future.

**Comment by cschleiden** [comment]
I hear you and we will think about it for future extensions :)

Dynamic decision points are good for flexibility  but bad for perf. The problem with dynamic is that I need to load your extension first in order to ask you. Declarative in the manifest is a lot easier for us to evaluate.

There are other options like constraints that we could provide and which are evaluated server side, but that requires some more thinking what would make sense to provide.

On Oct 28, 2017 10:53, Michael Thomsen <notifications@github.com> wrote:

No not preventing. I'm not saying customizeability is a bad thing. Far from it.
But I'd like the experience after installing to be as good as possible and make sense to the user while not being intrusive (showing up in places where it doesn't make sense in 95% of cases).

I don't have a real immediate use case for this today. Just wanted to make sure this is being considered in future planning. Some extension points like the backlog tabs do have a callback to show / hide them dynamically. Maybe that approach could be used more in the future.

**Comment by mpseidel** [comment]
Yeah good thinking. Happy to discuss further at some point if this comes up in your planning again :)
