### ISSUE TITLE
Feature request: All updates/changes in a day

### ISSUE THREAD

**Issue by MrTarantula** [microsoft/vss-web-extension-sdk#64]
It would be great to be able to query for all updates to all work items for a given day or date range. Right now there are several hoops. I query for items that have a ChangedDate = whateverDay, then `getWorkItems` and `getWorkItemUpdates`, which gives me a `workItemUpdate[][]` that I have to then flatten. And then I have to filter the result by the whateverDay.

This is also incomplete because if an item has a ChangedDate after the day, but has updates for that day, then it won't catch them. I'm sure that I could string a dozen promises together to get close, but it would be great if there was a core method like `getUpdatesForRange(startDay, endDay?, project?, team?)` or even `getWorkItemsByUpdatedDate(startDay, fields?, expand?, errorPolicy?)`.

**Comment by stansw** [comment]
@MrTarantula your descriptions sounds like a data export scenario. You may consider using Analytics Service which is already powering data export scenario for Power BI integration.

https://docs.microsoft.com/en-us/vsts/report/analytics/what-is-analytics
https://docs.microsoft.com/en-us/vsts/report/extend-analytics/

The methods you asked for can be expressed with OData. For example, the query below gets all the updates in a given day. Please notice that with a single call you execute the query and specify the fields you are interested in.

```OData
https://{account}.analytics.visualstudio.com/_odata/v1.0/WorkItemRevisions
  ?$filter=ChangedDate ge 2017-01-01Z and ChangedDate lt 2017-01-02Z
  &$select=WorkItemRevisionSK, WorkItemId, Revision, Title, WorkItemType, State
```

If you want high accuracy you should replace `ChangedDate` with `AnalyticsUpdatedDate`. Otherwise you would miss updates to some fields such as `RevisedDate` which gets set only when a new revision is created.
```OData
https://{account}.analytics.visualstudio.com/_odata/v1.0/WorkItemRevisions
  ?$filter=AnalyticsUpdatedDate ge 2017-01-01Z and AnalyticsUpdatedDate lt 2017-01-02Z
  &$select=WorkItemRevisionSK, WorkItemId, Revision, Title, WorkItemType, State
```

**Comment by MrTarantula** [comment]
Looks like this isn't yet available for on-prem TFS, which is what my current project is running on. Also, if I wanted to release my extension to the public, it's less than ideal to require dependencies on other (possibly non-free in the future) extensions. This is good information though. I appreciate your response.
