### ISSUE TITLE
vss-web-estension-sdk uses tsd, but is deprecated

### ISSUE THREAD

**Issue by forrestcoward** [Microsoft/vss-web-extension-sdk#8]
TSD is deprecated: https://github.com/DefinitelyTyped/tsd/issues/269
Yet, the readme for this repository instruct using tsd.

**Comment by serkan-inci** [comment]
Thanks, we'll investigate this and try to switch to typings as soon as possible.

**Comment by jmezach** [comment]
Would you accept a PR for this?

**Comment by DrMueller** [comment]
Are there some news regarding that topic? Angular-CLI only supports typings afaik, therefore I can't get the  Intellisense support.

**Comment by cschleiden** [comment]
We use @types now, typings is also deprecated.

**Comment by DrMueller** [comment]
@cschleiden I can't find a repo for your types, is there an example around how to proceed with it?

**Comment by cschleiden** [comment]
@DrMueller What do you mean? The VSS types should come with the npm package.

**Comment by DrMueller** [comment]
@cschleiden I'm trying to make an VSTS extension work with the Angular CLI, which only interacts with the typings in the @types folder and their structure. Therefore, I can't make it compile with the sdk type definitions.

**Comment by cschleiden** [comment]
@DrMueller Hm.. but @types is only used if a package doesn't contain its own type definitions. The VSS sdk *does* contain type definitions (see the `types` setting in `package.json`, so that should work). 

See https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html, we use the first (the "favored") approach. I don't have any experience with angular-cli, but there must be a way to make that work.
